- name: Install MySQL libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL
  
- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: installed